[font]
normal = { family = "M+1Code Nerd Font Mono", style = "Regular" }
offset = { x = 0, y = 2 }
size = 10

[keyboard]
bindings = [
	{ key = "F", mods = "Control | Shift", chars = "\u2660" },
	{ key = "Insert", mods = "Control", action = "Copy" },
	{ key = "Insert", mods = "Shift", action = "Paste" }
]
