#!/usr/bin/env bash
# this script is run in the same instance as the neovim window, allowing you
# to set up the environment of the neovim shell
#
# if you want to modify the terminal environment, you should look in the
# configs/ directory or the start.sh script generated by install.py

export INIT_PATH=$1
export PATHS=$2

nvim -u $INIT_PATH $PATHS
